name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up JDK 8
      uses: actions/setup-java@v3  # Updated to the latest version
      with:
        distribution: 'temurin'  # Use 'temurin' as 'adopt' is deprecated
        java-version: 8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-8-jdk \
          bc \
          bison \
          build-essential \
          curl \
          flex \
          g++-multilib \
          gcc-multilib \
          git \
          gnupg \
          gperf \
          imagemagick \
          lib32ncurses5-dev \
          lib32readline-dev \
          lib32z1-dev \
          liblz4-tool \
          libncurses5-dev \
          libsdl1.2-dev \
          libssl-dev \
          libxml2 \
          libxml2-utils \
          lzop \
          pngcrush \
          rsync \
          schedtool \
          squashfs-tools \
          xsltproc \
          zip \
          zlib1g-dev

    - name: Set up repo
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH  # Add repo to PATH

    - name: Initialize repo
      run: |
        mkdir -p ~/grapheneos
        cd ~/grapheneos
        repo init -u https://github.com/GrapheneOS/platform_manifest.git -b 13
        repo sync -c -j4

    - name: Start build
      run: |
        cd ~/grapheneos
        source build/envsetup.sh
        lunch aosp_cepheus-userdebug
        make -j$(nproc)
